apiVersion: v1
kind: List
items:
  - metadata:
      labels:
        name: weave-scope
      name: weave-scope
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Mon Apr 17 2017 01:43:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    apiVersion: v1
    kind: ServiceAccount
  - metadata:
      labels:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
      name: weave-scope-app
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Mon Apr 17 2017 01:43:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            name: weave-scope-app
            app: weave-scope
            weave-cloud-component: scope
            weave-scope-component: app
        spec:
          containers:
            - name: app
              image: 'weaveworks/scope:1.3.0'
              imagePullPolicy: IfNotPresent
              args:
                - '--no-probe'
              ports:
                - containerPort: 4040
                  protocol: TCP
      replicas: 1
    apiVersion: apps/v1beta1
    kind: Deployment
  - metadata:
      labels:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
      name: weave-scope-app
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Mon Apr 17 2017 01:43:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      type: NodePort
      ports:
        - name: app
          port: 80
          targetPort: 4040
          protocol: TCP
      selector:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
    apiVersion: v1
    kind: Service
  - metadata:
      labels:
        name: weave-scope-agent
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: agent
      name: weave-scope-agent
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Mon Apr 17 2017 01:43:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            name: weave-scope-agent
            app: weave-scope
            weave-cloud-component: scope
            weave-scope-component: agent
        spec:
          tolerations:
            - key: node-role.kubernetes.io/master
              effect: NoSchedule
          containers:
            - name: agent
              image: 'weaveworks/scope:1.3.0'
              imagePullPolicy: IfNotPresent
              args:
                - '--no-app'
                - '--probe.docker.bridge=docker0'
                - '--probe.docker=true'
                - '--probe.kubernetes=true'
                - >-
                  $(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)
              securityContext:
                privileged: true
              volumeMounts:
                - name: docker-socket
                  mountPath: /var/run/docker.sock
                - name: scope-plugins
                  mountPath: /var/run/scope/plugins
          volumes:
            - name: docker-socket
              hostPath:
                path: /var/run/docker.sock
            - name: scope-plugins
              hostPath:
                path: /var/run/scope/plugins
          hostPID: true
          hostNetwork: true
          serviceAccountName: weave-scope
    apiVersion: extensions/v1beta1
    kind: DaemonSet
  - metadata:
      labels:
        name: weave-scope
      name: weave-scope
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Mon Apr 17 2017 01:43:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    rules:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - '*'
      - nonResourceURLs:
          - '*'
        verbs:
          - '*'
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
  - metadata:
      labels:
        name: weave-scope
      name: weave-scope
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-9eec4bc",
            "original-request": {
              "url": "/k8s/v1.6/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Mon Apr 17 2017 01:43:31 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: weave-scope
    subjects:
      - kind: ServiceAccount
        name: weave-scope
        namespace: kube-system
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
